# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 274d7ce5e6216ee58e0fe280e183356caf4fb63b2b51b7705d54e3f3a09433d6f8e8b5b00c8ee3d55c62030a6078eaa62d8e99476eaa6f5afa1a675e6f420817

test:
  secret_key_base: 5cf005c82c3bbe841c44833eedc2b5d226ee79ba6a57d4bb41523d9201ec9089a939a3f35918f5366f25666816cb8626fd58f30c555ebb1e0236bb15ccdd9dc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
